@port = 15854

### HTML Page
GET http://localhost:{{port}} HTTP/1.1


### Get host list
GET http://localhost:{{port}}/hosts?hosts-file=./hosts.dat HTTP/1.1


## Default category

### Add host to default category
POST http://localhost:{{port}}/hosts?hosts-file=./hosts.dat HTTP/1.1
content-type: application/json

{
    "name": "test0",
    "address": "localhost",
    "port": 1022,
    "username": "testuser",
    "password": "1234",
    "privateKeyText": ""
}

### Edit host
POST http://localhost:{{port}}/hosts?hosts-file=./hosts.dat&host-idx=0 HTTP/1.1
content-type: application/json

{
    "name": "test1",
    "description": "",
    "address": "192.168.0.1",
    "port": 2022,
    "username": "user1",
    "password": "user1234",
    "private-key-text": ""
}

### Delete host
DELETE http://localhost:{{port}}/hosts?hosts-file=./hosts.dat&category-idx=0&host-idx=1 HTTP/1.1


## Category usage

### Add category
POST http://localhost:{{port}}/categories?hosts-file=./hosts.dat HTTP/1.1
content-type: application/json

{
    "name": "cate01"
}

### Edit category
POST http://localhost:{{port}}/categories?hosts-file=./hosts.dat&category-idx=1 HTTP/1.1
content-type: application/json

{
    "name": "cate00"
}

### Delete category
DELETE http://localhost:{{port}}/categories?hosts-file=./hosts.dat&idx=1 HTTP/1.1


### Add host
POST http://localhost:{{port}}/hosts?hosts-file=./hosts.dat&category-idx=1 HTTP/1.1
content-type: application/json

{
    "name": "test0",
    "address": "localhost",
    "port": 1022,
    "username": "testuser",
    "password": "1234",
    "privateKeyText": ""
}

### Edit host
POST http://localhost:{{port}}/hosts?hosts-file=./hosts.dat&category-idx=1&host-idx=0 HTTP/1.1
content-type: application/json

{
    "name": "test1",
    "description": "",
    "address": "192.168.0.1",
    "port": 2022,
    "username": "user1",
    "password": "user1234",
    "private-key-text": ""
}

### Delete host
DELETE http://localhost:{{port}}/hosts?hosts-file=./hosts.dat&category-idx=1&host-idx=0 HTTP/1.1


### Change host file password
PUT http://localhost:{{port}}/host-file-password?hosts-file=./hosts.dat HTTP/1.1
content-type: application/json

{
    "password-old": "1",
    "password-new": "1234"
}
